#!/usr/bin/env sh

if [ ! -z "$CRON_CONTAINER" ]; then
    echo "* * * * * run-parts /etc/periodic/1min" >> /etc/crontabs/root
    exec crond -f -l 8
else

    usermod -u 1000 sail

    if [ ! -d /.composer ]; then
        mkdir /.composer
    fi

    chmod -R ugo+rw /.composer
    chmod -R ugo+rw storage bootstrap/cache

    if [ $# -gt 0 ];then
        exec su-exec 1000 "$@"
    else
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    fi

fi
